### ISSUE TITLE
Testsuite

### ISSUE THREAD

**Issue by gsilvis** [gsilvis/silvos#15]
This is needed to catch regressions that are more subtle than "everything broke".

**Comment by gsilvis** [comment]
Several bits of preparation are done:
-Console output, usable from userland.
-Shutdown, so tests can actually ever end

It should be possible to /not/ pass an IDE disk, and safely disable the disk syscalls, so tests can be parallelized.

But, at this point, everything but the peripherals should be testable.

**Comment by allanlw** [comment]
With #13, #17 and #18, this might reasonably be considered "done".

**Comment by gsilvis** [comment]
There's plenty more features to test!  Until we test interleaving of threads somehow, and probably also test the disk driver, I'm going to leave this open

**Comment by allanlw** [comment]
My understanding of this issue, based off of the report in the first entry, is that it is for the existence of the testsuite itself, possibly including some tests to demonstrate that it works.

Increasing test coverage for untested portions of the kernel should really be split into separate issues.

**Comment by gsilvis** [comment]
Now that we have fork, I'm going to follow allanlw's advice and close this
