### ISSUE TITLE
Race condition in kbd.c

### ISSUE THREAD

**Issue by frozencemetery** [gsilvis/silvos#16]
As per [L66](https://github.com/gsilvis/silvos/blob/0ba34bbd77399f5631192cbce4bb8bda3b20ce35/kernel/kbd.c#L66), 0ba34bbd77399f5631192cbce4bb8bda3b20ce35 introduces a race condition.

Opening this issue mostly because I want to see how you solve it.

**Comment by gsilvis** [comment]
The behavior right now is:  if multiple threads are already waiting, and two keystrokes come in close to eachother, there's no guarantee as to which keystroke goes to which thread.  This is benign enough that I don't see any reason to fix it yet.  I may just document getch as having this property, then fix it later as an 'enhancement'

**Comment by gsilvis** [comment]
This was fixed in pr #76
