### ISSUE TITLE
test-memory-reap breaks on -O0

### ISSUE THREAD

**Issue by gsilvis** [gsilvis/silvos#32]

**Comment by allanlw** [comment]
So does `test-memory`, because it doesn't link.

**Comment by allanlw** [comment]
I think this bug is invalid. It's slow, but finishes in about 10 seconds on my machine.

**Comment by gsilvis** [comment]
test-memory breaks when the userland is at -O0.  test-memory-reap breaks when the kernel is at -O0

**Comment by allanlw** [comment]
Ah, that makes sense.

Turns out test-float-fib also doesn't work if the kernel is -O0

**Comment by allanlw** [comment]
Actually, with the kernel -O0 (and userland -O2) the following tests fail:

- test-memory-reap
- test-memory
- test-float-fib
- test-fork

this is likely a bug in the fork syscall, which all of these share.

**Comment by gsilvis** [comment]
This was broken by fc05b705dee6a1bbc5b047578e15ea21873e5887
