### ISSUE TITLE
Everything breaks at -O3

### ISSUE THREAD

**Issue by gsilvis** [gsilvis/silvos#36]
Most likely we're missing some 'volatile' and such.  @cstanfill suggests putting some effort into this now, lest it become totally impossible later.

**Comment by gsilvis** [comment]
One problem:  GCC emits MMX/SSE/etc instructions, and uses the registers.  This immediately triggers a fault, because those aren't allowed in the kernel.  So, those extensions should be disabled.

**Comment by allanlw** [comment]
This was fixed by #37 !

**Comment by gsilvis** [comment]
Until the testsuite actively checks this, I think we should keep this open
