### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by gsilvis** [gsilvis/silvos#40]
We should set something on travis-CI.  Since we need a somewhat custom cross-compiler and qemu, we might want to use a docker file to set up everything we need

**Comment by allanlw** [comment]
I recommend setting up docker cloud for this.

**Comment by cstanfill** [comment]
I don't see any reason, looking at travis, that we can't just install qemu through apt and george's cross-compiler .debs by downloading them from somewhere (I was going to put it on my AWS S3 for now).

**Comment by allanlw** [comment]
Just build the cross compiler each time.

**Comment by cstanfill** [comment]
Well I have a good reason I can't install the cross-compiler from @gsilvis's .debs and it's that travis runs on ubuntu Trusty which is missing some deps. So I can either do what @allanlw suggested or wrap the whole thing in a debian stable Docker image (seriously, when you're too old for debian stable packages, you're too old :|)
