### ISSUE TITLE
trigger_is_level impossible to be set in analyze_madt_entry

### ISSUE THREAD

**Issue by crowell** [gsilvis/silvos#83]
https://github.com/gsilvis/silvos/blob/master/kernel/apic.c#L144

`uint8_t trigger_is_level = ((flags & 0x0C) == 0x11);`

the upper nibble will never have anything set in `flags & 0x0C`

trigger_is_level will always be 0

**Comment by gsilvis** [comment]
Huh, yeah, that's clearly wrong.  I'll look up the MADT format again and figure out what the right comparison is.
